version: '3.6'
services:
  postgres:
    container_name: hasura-postgres
    image: postgres:12
    restart: always
    volumes:
    - ./db_data/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    container_name: hasura-graphql-engine
    image: hasura/graphql-engine:v2.1.1.cli-migrations-v3
    volumes:
      - ../hasura/migrations:/hasura-migrations
      - ../hasura/metadata:/hasura-metadata
    ports:
    - "8081:8080"
    depends_on:
    - "postgres"
    restart: always
    env_file:
      - .env